// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Copyright (c) DUSK NETWORK. All rights reserved.

//! Schema tests for the test contract.
//!
//! These tests load the data-driver WASM and verify that the schema
//! generated by the `#[contract]` macro is correct.

mod test_session;

use wasmtime::*;

const DATA_DRIVER_WASM: &[u8] =
    include_bytes!("../../../target/data-driver/wasm32-unknown-unknown/release/test_contract.wasm");

/// Load the data-driver WASM and call get_schema to retrieve the contract schema.
fn get_schema_from_wasm() -> String {
    let engine = Engine::default();
    let module = Module::new(&engine, DATA_DRIVER_WASM).expect("Failed to compile WASM");

    let mut store = Store::new(&engine, ());
    let instance = Instance::new(&mut store, &module, &[]).expect("Failed to instantiate WASM");

    // Get the memory
    let memory = instance
        .get_memory(&mut store, "memory")
        .expect("Failed to get memory");

    // Call init() first to register the driver
    let init = instance
        .get_typed_func::<(), ()>(&mut store, "init")
        .expect("Failed to get init function");
    init.call(&mut store, ()).expect("Failed to call init");

    // Get get_schema function
    let get_schema = instance
        .get_typed_func::<(i32, i32), i32>(&mut store, "get_schema")
        .expect("Failed to get get_schema function");

    // Use a fixed offset in linear memory for the output buffer
    let buf_offset: i32 = 1024 * 64; // 64KB offset should be safe
    let buf_size: i32 = 16 * 1024; // 16KB buffer

    // Ensure memory is large enough
    let current_pages = memory.size(&store);
    let needed_pages = ((buf_offset + buf_size) as u64 + 65535) / 65536;
    if current_pages < needed_pages {
        memory
            .grow(&mut store, needed_pages - current_pages)
            .expect("Failed to grow memory");
    }

    // Call get_schema
    let result = get_schema
        .call(&mut store, (buf_offset, buf_size))
        .expect("Failed to call get_schema");

    // Check for errors (ErrorCode::Ok = 0)
    assert_eq!(result, 0, "get_schema returned error code: {result}");

    // Read the result from memory
    // Format: 4-byte little-endian length prefix, then data
    let data = memory.data(&store);
    let len_bytes = &data[buf_offset as usize..buf_offset as usize + 4];
    let len = u32::from_le_bytes([len_bytes[0], len_bytes[1], len_bytes[2], len_bytes[3]]) as usize;

    let schema_start = buf_offset as usize + 4;
    let schema_bytes = &data[schema_start..schema_start + len];
    String::from_utf8(schema_bytes.to_vec()).expect("Schema is not valid UTF-8")
}

#[test]
fn test_schema_contract_name() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    assert_eq!(schema["name"], "TestContract");
}

#[test]
fn test_schema_has_functions() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let functions = schema["functions"]
        .as_array()
        .expect("functions should be an array");
    let fn_names: Vec<&str> = functions
        .iter()
        .map(|f| f["name"].as_str().unwrap())
        .collect();

    // Check inherent methods are present
    assert!(fn_names.contains(&"init"), "missing init");
    assert!(fn_names.contains(&"counter"), "missing counter");
    assert!(fn_names.contains(&"label"), "missing label");
    assert!(fn_names.contains(&"set_counter"), "missing set_counter");
    assert!(fn_names.contains(&"update"), "missing update");
    assert!(fn_names.contains(&"reset_counter"), "missing reset_counter");
    assert!(fn_names.contains(&"add_item"), "missing add_item");
    assert!(fn_names.contains(&"get_item"), "missing get_item");

    // Check exposed trait methods are present
    assert!(fn_names.contains(&"owner"), "missing owner");
    assert!(
        fn_names.contains(&"transfer_ownership"),
        "missing transfer_ownership"
    );
    assert!(
        fn_names.contains(&"renounce_ownership"),
        "missing renounce_ownership"
    );

    // Check private methods are NOT present
    assert!(
        !fn_names.contains(&"only_owner"),
        "only_owner should not be exported"
    );
    assert!(
        !fn_names.contains(&"owner_mut"),
        "owner_mut should not be exported"
    );
}

#[test]
fn test_schema_has_events() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let events = schema["events"]
        .as_array()
        .expect("events should be an array");
    let event_topics: Vec<&str> = events
        .iter()
        .map(|e| e["topic"].as_str().unwrap())
        .collect();

    // Check event topics
    assert!(
        event_topics.iter().any(|t| t.contains("CounterReset")),
        "missing CounterReset event"
    );
    assert!(
        event_topics.iter().any(|t| t.contains("CounterUpdated")),
        "missing CounterUpdated event"
    );
    assert!(
        event_topics.iter().any(|t| t.contains("Item")),
        "missing Item event"
    );
}

#[test]
fn test_schema_has_imports() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let imports = schema["imports"]
        .as_array()
        .expect("imports should be an array");
    let import_names: Vec<&str> = imports
        .iter()
        .map(|i| i["name"].as_str().unwrap())
        .collect();

    // Check key imports
    assert!(import_names.contains(&"Item"), "missing Item import");
    assert!(import_names.contains(&"ItemId"), "missing ItemId import");
    assert!(import_names.contains(&"events"), "missing events import");
}

#[test]
#[ignore]
fn print_schema() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");
    println!("{}", serde_json::to_string_pretty(&schema).unwrap());
}

/// Helper struct for calling data-driver functions via WASM.
struct DataDriverWasm {
    store: Store<()>,
    instance: Instance,
}

impl DataDriverWasm {
    fn new() -> Self {
        let engine = Engine::default();
        let module = Module::new(&engine, DATA_DRIVER_WASM).expect("Failed to compile WASM");

        let mut store = Store::new(&engine, ());
        let instance = Instance::new(&mut store, &module, &[]).expect("Failed to instantiate WASM");

        // Call init() to register the driver
        let init = instance
            .get_typed_func::<(), ()>(&mut store, "init")
            .expect("Failed to get init function");
        init.call(&mut store, ()).expect("Failed to call init");

        Self { store, instance }
    }

    /// Call get_last_error to retrieve the error message after a failed operation.
    fn get_last_error(&mut self) -> String {
        let memory = self
            .instance
            .get_memory(&mut self.store, "memory")
            .expect("Failed to get memory");

        let get_error = self
            .instance
            .get_typed_func::<(i32, i32), i32>(&mut self.store, "get_last_error")
            .expect("Failed to get get_last_error function");

        let out_offset = 1024 * 16;
        let out_size = 4096;

        let result = get_error
            .call(&mut self.store, (out_offset as i32, out_size as i32))
            .expect("Failed to call get_last_error");

        if result != 0 {
            return format!("get_last_error failed with code {result}");
        }

        let data = memory.data(&self.store);
        let len_bytes = &data[out_offset..out_offset + 4];
        let len =
            u32::from_le_bytes([len_bytes[0], len_bytes[1], len_bytes[2], len_bytes[3]]) as usize;
        String::from_utf8_lossy(&data[out_offset + 4..out_offset + 4 + len]).to_string()
    }

    /// Call encode_input_fn via the WASM interface.
    fn encode_input(&mut self, fn_name: &str, json: &str) -> Result<Vec<u8>, String> {
        let memory = self
            .instance
            .get_memory(&mut self.store, "memory")
            .expect("Failed to get memory");

        // Grow memory if needed
        let current_pages = memory.size(&self.store);
        if current_pages < 4 {
            memory
                .grow(&mut self.store, 4 - current_pages)
                .expect("Failed to grow memory");
        }

        let encode_fn = self
            .instance
            .get_typed_func::<(i32, i32, i32, i32, i32, i32), i32>(
                &mut self.store,
                "encode_input_fn",
            )
            .expect("Failed to get encode_input_fn function");

        // Write fn_name to memory
        let fn_name_offset = 1024;
        let fn_name_bytes = fn_name.as_bytes();
        memory.data_mut(&mut self.store)[fn_name_offset..fn_name_offset + fn_name_bytes.len()]
            .copy_from_slice(fn_name_bytes);

        // Write json to memory
        let json_offset = fn_name_offset + 256;
        let json_bytes = json.as_bytes();
        memory.data_mut(&mut self.store)[json_offset..json_offset + json_bytes.len()]
            .copy_from_slice(json_bytes);

        // Output buffer
        let out_offset = json_offset + 4096;
        let out_size = 4096;

        let result = encode_fn
            .call(
                &mut self.store,
                (
                    fn_name_offset as i32,
                    fn_name_bytes.len() as i32,
                    json_offset as i32,
                    json_bytes.len() as i32,
                    out_offset as i32,
                    out_size as i32,
                ),
            )
            .expect("Failed to call encode_input_fn");

        if result != 0 {
            let msg = self.get_last_error();
            return Err(format!("Error code {result}: {msg}"));
        }

        // Read successful result (4-byte length prefix + data)
        let data = memory.data(&self.store);
        let len_bytes = &data[out_offset..out_offset + 4];
        let len =
            u32::from_le_bytes([len_bytes[0], len_bytes[1], len_bytes[2], len_bytes[3]]) as usize;
        Ok(data[out_offset + 4..out_offset + 4 + len].to_vec())
    }

    /// Call decode_output_fn via the WASM interface.
    fn decode_output(&mut self, fn_name: &str, rkyv: &[u8]) -> Result<serde_json::Value, String> {
        self.decode_with_name("decode_output_fn", fn_name, rkyv)
    }

    /// Call decode_event via the WASM interface.
    fn decode_event(&mut self, event_name: &str, rkyv: &[u8]) -> Result<serde_json::Value, String> {
        self.decode_with_name("decode_event", event_name, rkyv)
    }

    /// Generic decode helper for decode_output_fn and decode_event.
    fn decode_with_name(
        &mut self,
        wasm_fn: &str,
        name: &str,
        rkyv: &[u8],
    ) -> Result<serde_json::Value, String> {
        let memory = self
            .instance
            .get_memory(&mut self.store, "memory")
            .expect("Failed to get memory");

        let decode_fn = self
            .instance
            .get_typed_func::<(i32, i32, i32, i32, i32, i32), i32>(&mut self.store, wasm_fn)
            .unwrap_or_else(|_| panic!("Failed to get {wasm_fn} function"));

        // Write name to memory
        let name_offset = 1024;
        let name_bytes = name.as_bytes();
        memory.data_mut(&mut self.store)[name_offset..name_offset + name_bytes.len()]
            .copy_from_slice(name_bytes);

        // Write rkyv data to memory
        let rkyv_offset = name_offset + 256;
        memory.data_mut(&mut self.store)[rkyv_offset..rkyv_offset + rkyv.len()]
            .copy_from_slice(rkyv);

        // Output buffer
        let out_offset = rkyv_offset + 4096;
        let out_size = 4096;

        let result = decode_fn
            .call(
                &mut self.store,
                (
                    name_offset as i32,
                    name_bytes.len() as i32,
                    rkyv_offset as i32,
                    rkyv.len() as i32,
                    out_offset as i32,
                    out_size as i32,
                ),
            )
            .unwrap_or_else(|_| panic!("Failed to call {wasm_fn}"));

        if result != 0 {
            let msg = self.get_last_error();
            return Err(format!("Error code {result}: {msg}"));
        }

        // Read successful result (4-byte length prefix + JSON data)
        let data = memory.data(&self.store);
        let len_bytes = &data[out_offset..out_offset + 4];
        let len =
            u32::from_le_bytes([len_bytes[0], len_bytes[1], len_bytes[2], len_bytes[3]]) as usize;
        let json_str = String::from_utf8_lossy(&data[out_offset + 4..out_offset + 4 + len]);
        serde_json::from_str(&json_str).map_err(|e| e.to_string())
    }
}

#[test]
fn test_custom_data_driver_function_encode() {
    let mut driver = DataDriverWasm::new();

    // Test encoding a u64 via the custom "raw_id" function
    let input_json = "42";
    let encoded = driver
        .encode_input("raw_id", input_json)
        .expect("Failed to encode raw_id");

    assert_eq!(encoded.len(), 8, "Expected 8 bytes for u64");
    assert_eq!(encoded, 42u64.to_le_bytes().to_vec());
}

#[test]
fn test_custom_data_driver_function_decode() {
    let mut driver = DataDriverWasm::new();

    // Test decoding raw bytes back to u64 via the custom "raw_id" function
    let rkyv_data = 42u64.to_le_bytes().to_vec();
    let decoded = driver
        .decode_output("raw_id", &rkyv_data)
        .expect("Failed to decode raw_id");

    assert_eq!(decoded, serde_json::json!(42));
}

#[test]
fn test_custom_data_driver_function_roundtrip() {
    let mut driver = DataDriverWasm::new();

    let original_json = "12345";
    let encoded = driver
        .encode_input("raw_id", original_json)
        .expect("Failed to encode raw_id");

    let decoded = driver
        .decode_output("raw_id", &encoded)
        .expect("Failed to decode raw_id");

    assert_eq!(decoded, serde_json::json!(12345));
}

// =============================================================================
// Tests for #[contract(feeds = "Type")] attribute
// =============================================================================

#[test]
fn test_schema_has_feed_functions() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let functions = schema["functions"]
        .as_array()
        .expect("functions should be an array");
    let fn_names: Vec<&str> = functions
        .iter()
        .map(|f| f["name"].as_str().unwrap())
        .collect();

    assert!(fn_names.contains(&"items"), "missing items");
    assert!(fn_names.contains(&"item_ids"), "missing item_ids");

    // Verify the schema shows () as output (the Rust return type)
    let items_fn = functions
        .iter()
        .find(|f| f["name"] == "items")
        .expect("items not found");
    assert_eq!(
        items_fn["output"].as_str().unwrap(),
        "()",
        "items should have () as output in schema"
    );
}

#[test]
fn test_feed_function_decode_uses_feed_type() {
    use types::{Item, ItemId};

    let mut driver = DataDriverWasm::new();

    // Create test data: (ItemId, Item) tuple
    let item_id = ItemId(1);
    let item = Item {
        id: item_id,
        value: 1000,
        active: true,
    };

    // Serialize the tuple using rkyv
    let rkyv_data = rkyv::to_bytes::<_, 256>(&(item_id, item)).expect("Failed to serialize tuple");

    // Decode using the data-driver — uses the feed_type "(ItemId, Item)"
    let decoded = driver
        .decode_output("items", &rkyv_data)
        .expect("Failed to decode items output");

    // Verify we got an array (tuple serializes as array in JSON)
    assert!(
        decoded.is_array(),
        "Expected array (tuple), got: {decoded:?}"
    );

    let arr = decoded.as_array().unwrap();
    assert_eq!(arr.len(), 2, "Expected 2-element tuple");

    // First element is ItemId
    assert!(
        !arr[0].is_null(),
        "First element (ItemId) should not be null: {decoded:?}"
    );

    // Second element is Item struct
    assert!(arr[1].is_object(), "Second element should be Item object");
    assert!(arr[1]["value"].is_number(), "Item should have value field");
    assert_eq!(arr[1]["value"], 1000);
    assert_eq!(arr[1]["active"], true);
}

#[test]
fn test_feed_function_simple_type_decode() {
    use types::ItemId;

    let mut driver = DataDriverWasm::new();

    let item_id = ItemId(42);

    let rkyv_data = rkyv::to_bytes::<_, 256>(&item_id).expect("Failed to serialize ItemId");

    // Decode using the data-driver — uses the feed_type "ItemId"
    let decoded = driver
        .decode_output("item_ids", &rkyv_data)
        .expect("Failed to decode item_ids output");

    // ItemId should not be null
    assert!(
        !decoded.is_null(),
        "Expected non-null ItemId, got null. The feeds attribute is not working!"
    );

    // ItemId(42) should decode to 42
    assert_eq!(decoded, serde_json::json!(42));
}

// =============================================================================
// Tests for decode_event (using actual contract events)
// =============================================================================

use std::sync::LazyLock;

use dusk_core::abi::ContractId;
use dusk_core::dusk;
use dusk_core::signatures::bls::{PublicKey as AccountPublicKey, SecretKey as AccountSecretKey};
use rand::SeedableRng;
use rand::rngs::StdRng;
use test_session::TestSession;
use types::{Item, ItemId};

const CONTRACT_BYTECODE: &[u8] =
    include_bytes!("../../../target/contract/wasm32-unknown-unknown/release/test_contract.wasm");
const CONTRACT_ID: ContractId = ContractId::from_bytes([1; 32]);
const DEPLOYER: [u8; 64] = [0u8; 64];
const INITIAL_BALANCE: u64 = dusk(1_000.0);

static OWNER_SK: LazyLock<AccountSecretKey> = LazyLock::new(|| {
    let mut rng = StdRng::seed_from_u64(0x5EAF00D);
    AccountSecretKey::random(&mut rng)
});
static OWNER_PK: LazyLock<AccountPublicKey> = LazyLock::new(|| AccountPublicKey::from(&*OWNER_SK));

/// Set up a contract session for event tests.
fn setup_contract_session() -> TestSession {
    let mut session = TestSession::instantiate(vec![(&*OWNER_PK, INITIAL_BALANCE)], vec![]);

    session
        .deploy(
            CONTRACT_BYTECODE,
            dusk_vm::ContractData::builder()
                .owner(DEPLOYER)
                .init_arg(&(*OWNER_PK,))
                .contract_id(CONTRACT_ID),
        )
        .expect("Deploying test contract should succeed");

    session
}

#[test]
fn test_decode_event_counter_reset() {
    // 1. Call the contract to emit a real event
    let mut session = setup_contract_session();
    let receipt = session
        .call_public::<_, ()>(&OWNER_SK, CONTRACT_ID, "reset_counter", &())
        .expect("reset_counter should succeed");

    // 2. Extract the event from the receipt
    assert!(
        !receipt.events.is_empty(),
        "reset_counter should emit an event"
    );
    let event = &receipt.events[0];
    assert_eq!(event.topic, "counter_reset");

    // 3. Decode the event using the data-driver
    let mut driver = DataDriverWasm::new();
    let decoded = driver
        .decode_event(&event.topic, &event.data)
        .expect("Failed to decode CounterReset event");

    // CounterReset is a unit struct, may serialize to null or empty array
    assert!(
        decoded.is_null() || (decoded.is_array() && decoded.as_array().unwrap().is_empty()),
        "CounterReset should serialize to null or empty array, got: {decoded:?}"
    );
}

#[test]
fn test_decode_event_item_added() {
    // 1. Call the contract to emit a real item_added event
    let mut session = setup_contract_session();

    let item = Item {
        id: ItemId(1),
        value: 1000,
        active: true,
    };

    let receipt = session
        .call_public::<_, ()>(&OWNER_SK, CONTRACT_ID, "add_item", &item)
        .expect("add_item should succeed");

    // 2. Find the item_added event
    let event = receipt
        .events
        .iter()
        .find(|e| e.topic == "item_added")
        .expect("add_item should emit item_added event");

    // 3. Decode the event using the data-driver
    let mut driver = DataDriverWasm::new();
    let decoded = driver
        .decode_event(&event.topic, &event.data)
        .expect("Failed to decode Item event");

    // Verify the decoded fields match what we sent
    assert!(decoded.is_object(), "Item event should be an object");
    assert_eq!(decoded["value"], 1000);
    assert_eq!(decoded["active"], true);
}

// =============================================================================
// Negative tests for error handling
// =============================================================================

#[test]
fn test_encode_input_unknown_function() {
    let mut driver = DataDriverWasm::new();

    let result = driver.encode_input("nonexistent_function", "{}");

    assert!(result.is_err(), "Should fail for unknown function");
    let err = result.unwrap_err();
    assert!(
        err.contains("unknown fn") || err.contains("Unknown"),
        "Error should mention unknown function: {err}"
    );
}

#[test]
fn test_encode_input_malformed_json() {
    let mut driver = DataDriverWasm::new();

    let result = driver.encode_input("reset_counter", "not valid json {{{");

    assert!(result.is_err(), "Should fail for malformed JSON");
}

#[test]
fn test_decode_output_unknown_function() {
    let mut driver = DataDriverWasm::new();

    let result = driver.decode_output("nonexistent_function", &[]);

    assert!(result.is_err(), "Should fail for unknown function");
    let err = result.unwrap_err();
    assert!(
        err.contains("unknown fn") || err.contains("Unknown"),
        "Error should mention unknown function: {err}"
    );
}

#[test]
fn test_decode_output_malformed_rkyv() {
    let mut driver = DataDriverWasm::new();

    let result = driver.decode_output("counter", &[0xFF, 0xFF, 0xFF]);

    assert!(result.is_err(), "Should fail for malformed rkyv data");
}

#[test]
fn test_decode_event_unknown_topic() {
    let mut driver = DataDriverWasm::new();

    let result = driver.decode_event("unknown_event_topic", &[]);

    assert!(result.is_err(), "Should fail for unknown event topic");
    let err = result.unwrap_err();
    assert!(
        err.contains("unknown event") || err.contains("Unknown"),
        "Error should mention unknown event: {err}"
    );
}

// =============================================================================
// Schema detail verification tests
// =============================================================================

#[test]
fn test_schema_function_input_output_types() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let functions = schema["functions"]
        .as_array()
        .expect("functions should be an array");

    // Test counter: no input, returns u64
    let counter = functions
        .iter()
        .find(|f| f["name"] == "counter")
        .expect("counter should exist");
    assert_eq!(counter["input"], "()", "counter input should be ()");
    assert_eq!(counter["output"], "u64", "counter output should be u64");

    // Test init: takes PublicKey, returns ()
    let init = functions
        .iter()
        .find(|f| f["name"] == "init")
        .expect("init should exist");
    let init_input = init["input"].as_str().unwrap();
    assert!(
        init_input.contains("PublicKey"),
        "init input should contain PublicKey: {init_input}"
    );
    assert_eq!(init["output"], "()", "init output should be ()");

    // Test set_counter: takes u64, returns ()
    let set_counter = functions
        .iter()
        .find(|f| f["name"] == "set_counter")
        .expect("set_counter should exist");
    assert_eq!(
        set_counter["input"], "u64",
        "set_counter input should be u64"
    );
    assert_eq!(
        set_counter["output"], "()",
        "set_counter output should be ()"
    );

    // Test add_item: takes Item type, returns ()
    let add_item = functions
        .iter()
        .find(|f| f["name"] == "add_item")
        .expect("add_item should exist");
    let add_item_input = add_item["input"].as_str().unwrap();
    assert!(
        add_item_input.contains("Item"),
        "add_item input should contain Item: {add_item_input}"
    );
    assert_eq!(add_item["output"], "()", "add_item output should be ()");

    // Test get_item: takes ItemId, returns Option<Item>
    let get_item = functions
        .iter()
        .find(|f| f["name"] == "get_item")
        .expect("get_item should exist");
    let get_item_input = get_item["input"].as_str().unwrap();
    let get_item_output = get_item["output"].as_str().unwrap();
    assert!(
        get_item_input.contains("ItemId"),
        "get_item input should contain ItemId: {get_item_input}"
    );
    assert!(
        get_item_output.contains("Option") && get_item_output.contains("Item"),
        "get_item output should be Option<Item>: {get_item_output}"
    );
}

#[test]
fn test_schema_function_with_multiple_params() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let functions = schema["functions"]
        .as_array()
        .expect("functions should be an array");

    // Test update: takes (u64, String)
    let update = functions
        .iter()
        .find(|f| f["name"] == "update")
        .expect("update should exist");
    let input = update["input"].as_str().unwrap();

    assert!(
        input.contains("u64"),
        "update input should contain u64: {input}"
    );
    assert!(
        input.contains("String"),
        "update input should contain String: {input}"
    );
}

#[test]
fn test_schema_doc_comments() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let functions = schema["functions"]
        .as_array()
        .expect("functions should be an array");

    // counter has doc comment about "counter value"
    let counter = functions
        .iter()
        .find(|f| f["name"] == "counter")
        .expect("counter should exist");
    let doc = counter["doc"].as_str().unwrap_or("");
    assert!(
        doc.contains("counter"),
        "counter doc should mention 'counter', got: {doc}"
    );

    // set_counter has doc comment about "Sets the counter"
    let set_counter = functions
        .iter()
        .find(|f| f["name"] == "set_counter")
        .expect("set_counter should exist");
    let doc = set_counter["doc"].as_str().unwrap_or("");
    assert!(
        doc.contains("Sets"),
        "set_counter doc should mention 'Sets', got: {doc}"
    );

    // label has doc comment about "reference to the label"
    let label = functions
        .iter()
        .find(|f| f["name"] == "label")
        .expect("label should exist");
    let doc = label["doc"].as_str().unwrap_or("");
    assert!(
        doc.contains("label"),
        "label doc should mention 'label', got: {doc}"
    );
}

#[test]
fn test_schema_event_details() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let events = schema["events"]
        .as_array()
        .expect("events should be an array");

    // Find CounterUpdated event and verify data type
    let counter_updated = events
        .iter()
        .find(|e| {
            e["topic"]
                .as_str()
                .map(|t| t.contains("CounterUpdated"))
                .unwrap_or(false)
        })
        .expect("CounterUpdated event should exist");

    let data_type = counter_updated["data"].as_str().unwrap();
    assert!(
        data_type.contains("CounterUpdated"),
        "CounterUpdated data type should contain CounterUpdated: {data_type}"
    );

    // Find Item event (item_added or item_removed)
    let item_event = events
        .iter()
        .find(|e| {
            e["topic"]
                .as_str()
                .map(|t| t.contains("Item"))
                .unwrap_or(false)
        })
        .expect("Item event should exist");

    let data_type = item_event["data"].as_str().unwrap();
    assert!(
        data_type.contains("Item"),
        "Item event data type should contain Item: {data_type}"
    );
}

#[test]
fn test_schema_import_paths() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let imports = schema["imports"]
        .as_array()
        .expect("imports should be an array");

    // Verify Item import has full path
    let item_import = imports
        .iter()
        .find(|i| i["name"] == "Item")
        .expect("Item import should exist");

    let path = item_import["path"].as_str().unwrap();
    assert!(
        path.contains("types"),
        "Item path should be fully qualified with types: {path}"
    );

    // Verify ItemId import
    let item_id_import = imports
        .iter()
        .find(|i| i["name"] == "ItemId")
        .expect("ItemId import should exist");

    let path = item_id_import["path"].as_str().unwrap();
    assert!(
        path.contains("types"),
        "ItemId path should be fully qualified: {path}"
    );

    // Verify events import
    let events_import = imports
        .iter()
        .find(|i| i["name"] == "events")
        .expect("events import should exist");

    let path = events_import["path"].as_str().unwrap();
    assert!(
        path.contains("types"),
        "events path should be qualified: {path}"
    );
}

#[test]
fn test_schema_custom_flag() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let functions = schema["functions"]
        .as_array()
        .expect("functions should be an array");

    // Regular functions should have custom = false
    let counter = functions
        .iter()
        .find(|f| f["name"] == "counter")
        .expect("counter should exist");
    assert_eq!(counter["custom"], false, "counter should not be custom");

    let set_counter = functions
        .iter()
        .find(|f| f["name"] == "set_counter")
        .expect("set_counter should exist");
    assert_eq!(
        set_counter["custom"], false,
        "set_counter should not be custom"
    );
}

#[test]
fn test_schema_nested_generic_types() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let functions = schema["functions"]
        .as_array()
        .expect("functions should be an array");

    // Test find_item which returns Option<(ItemId, Item)>
    let fn_with_nested = functions
        .iter()
        .find(|f| f["name"] == "find_item")
        .expect("find_item should exist");

    let output_type = fn_with_nested["output"].as_str().unwrap();

    assert!(
        output_type.contains("Option"),
        "Output should be Option type: {output_type}"
    );
    assert!(
        output_type.contains("ItemId") || output_type.contains("("),
        "Output should contain tuple or ItemId: {output_type}"
    );
    assert!(
        output_type.contains("Item"),
        "Output should contain Item: {output_type}"
    );

    // Test that simpler Option types are also captured
    let get_item = functions
        .iter()
        .find(|f| f["name"] == "get_item")
        .expect("get_item should exist");

    let output_type = get_item["output"].as_str().unwrap();
    assert!(
        output_type.contains("Option"),
        "get_item output should be Option: {output_type}"
    );
    assert!(
        output_type.contains("Item"),
        "get_item output should contain Item: {output_type}"
    );
}

#[test]
fn test_schema_multiple_impl_blocks() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let functions = schema["functions"]
        .as_array()
        .expect("functions should be an array");
    let fn_names: Vec<&str> = functions
        .iter()
        .map(|f| f["name"].as_str().unwrap())
        .collect();

    // Functions from the FIRST impl block
    assert!(
        fn_names.contains(&"init"),
        "missing init from first impl block"
    );
    assert!(
        fn_names.contains(&"counter"),
        "missing counter from first impl block"
    );
    assert!(
        fn_names.contains(&"label"),
        "missing label from first impl block"
    );
    assert!(
        fn_names.contains(&"set_counter"),
        "missing set_counter from first impl block"
    );
    assert!(
        fn_names.contains(&"update"),
        "missing update from first impl block"
    );
    assert!(
        fn_names.contains(&"reset_counter"),
        "missing reset_counter from first impl block"
    );
    assert!(
        fn_names.contains(&"has_items"),
        "missing has_items from first impl block"
    );

    // Functions from the SECOND impl block
    assert!(
        fn_names.contains(&"add_item"),
        "missing add_item from second impl block"
    );
    assert!(
        fn_names.contains(&"get_item"),
        "missing get_item from second impl block"
    );
    assert!(
        fn_names.contains(&"find_item"),
        "missing find_item from second impl block"
    );
    assert!(
        fn_names.contains(&"contains_item"),
        "missing contains_item from second impl block"
    );
    assert!(
        fn_names.contains(&"remove_item"),
        "missing remove_item from second impl block"
    );
    assert!(
        fn_names.contains(&"items"),
        "missing items from second impl block"
    );
    assert!(
        fn_names.contains(&"item_ids"),
        "missing item_ids from second impl block"
    );

    // Functions from trait impls
    assert!(
        fn_names.contains(&"owner"),
        "missing owner from Ownable trait"
    );
    assert!(
        fn_names.contains(&"transfer_ownership"),
        "missing transfer_ownership from Ownable trait"
    );
    assert!(
        fn_names.contains(&"renounce_ownership"),
        "missing renounce_ownership from Ownable trait"
    );
    assert!(
        fn_names.contains(&"version"),
        "missing version from Versioned trait"
    );
}

// =============================================================================
// Schema structural compliance tests
// =============================================================================

#[test]
fn test_schema_is_valid_json() {
    let schema_json = get_schema_from_wasm();

    assert!(!schema_json.is_empty(), "Schema should not be empty");

    let result: Result<serde_json::Value, _> = serde_json::from_str(&schema_json);
    assert!(
        result.is_ok(),
        "Schema should be valid JSON: {:?}",
        result.err()
    );

    let schema = result.unwrap();
    assert!(schema.is_object(), "Schema root should be a JSON object");
}

#[test]
fn test_schema_has_required_top_level_fields() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let obj = schema.as_object().expect("Schema should be an object");

    assert!(obj.contains_key("name"), "Schema must have 'name' field");
    assert!(
        obj.contains_key("functions"),
        "Schema must have 'functions' field"
    );
    assert!(
        obj.contains_key("events"),
        "Schema must have 'events' field"
    );
    assert!(
        obj.contains_key("imports"),
        "Schema must have 'imports' field"
    );

    assert!(schema["name"].is_string(), "'name' must be a string");
    assert!(
        schema["functions"].is_array(),
        "'functions' must be an array"
    );
    assert!(schema["events"].is_array(), "'events' must be an array");
    assert!(schema["imports"].is_array(), "'imports' must be an array");
}

#[test]
fn test_schema_function_fields_consistent() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let functions = schema["functions"]
        .as_array()
        .expect("functions should be an array");

    for (i, func) in functions.iter().enumerate() {
        let func_obj = func
            .as_object()
            .unwrap_or_else(|| panic!("Function at index {i} should be an object"));

        assert!(
            func_obj.contains_key("name"),
            "Function at index {i} missing 'name' field"
        );
        assert!(
            func_obj.contains_key("input"),
            "Function at index {i} missing 'input' field"
        );
        assert!(
            func_obj.contains_key("output"),
            "Function at index {i} missing 'output' field"
        );
        assert!(
            func_obj.contains_key("custom"),
            "Function at index {i} missing 'custom' field"
        );
    }
}

#[test]
fn test_schema_event_fields_consistent() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let events = schema["events"]
        .as_array()
        .expect("events should be an array");

    for (i, event) in events.iter().enumerate() {
        let event_obj = event
            .as_object()
            .unwrap_or_else(|| panic!("Event at index {i} should be an object"));

        assert!(
            event_obj.contains_key("topic"),
            "Event at index {i} missing 'topic' field"
        );
        assert!(
            event_obj.contains_key("data"),
            "Event at index {i} missing 'data' field"
        );

        let topic = &event["topic"];
        assert!(
            topic.is_string(),
            "Event at index {i}: 'topic' must be string, got {topic:?}"
        );
    }
}

#[test]
fn test_schema_import_fields_consistent() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let imports = schema["imports"]
        .as_array()
        .expect("imports should be an array");

    for (i, import) in imports.iter().enumerate() {
        let import_obj = import
            .as_object()
            .unwrap_or_else(|| panic!("Import at index {i} should be an object"));

        assert!(
            import_obj.contains_key("name"),
            "Import at index {i} missing 'name' field"
        );
        assert!(
            import_obj.contains_key("path"),
            "Import at index {i} missing 'path' field"
        );

        let name = &import["name"];
        assert!(
            name.is_string(),
            "Import at index {i}: 'name' must be string, got {name:?}"
        );
    }
}

#[test]
fn test_schema_no_duplicate_function_names() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let functions = schema["functions"]
        .as_array()
        .expect("functions should be an array");
    let fn_names: Vec<&str> = functions
        .iter()
        .map(|f| f["name"].as_str().unwrap())
        .collect();

    let mut seen = std::collections::HashSet::new();
    for name in &fn_names {
        assert!(
            seen.insert(*name),
            "Duplicate function name in schema: {name}"
        );
    }
}

#[test]
fn test_schema_no_duplicate_event_topics() {
    let schema_json = get_schema_from_wasm();
    let schema: serde_json::Value =
        serde_json::from_str(&schema_json).expect("Failed to parse schema JSON");

    let events = schema["events"]
        .as_array()
        .expect("events should be an array");
    let topics: Vec<&str> = events
        .iter()
        .map(|e| e["topic"].as_str().unwrap())
        .collect();

    let mut seen = std::collections::HashSet::new();
    for topic in &topics {
        assert!(
            seen.insert(*topic),
            "Duplicate event topic in schema: {topic}"
        );
    }
}
